branches:
  - main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: chore
          scope: actions
          release: patch
  - "@semantic-release/github"
