name: mise project task
description: Setup mise and tools for project and run task
inputs:
  task:
    description: Task to run. Leave empty to not run task.
    required: false

runs:
  using: composite
  steps:
    - name: Setup environment for mise - unix
      if: runner.os != 'Windows'
      run: |
        MISE_DATA_DIR="${RUNNER_TEMP}/.mise"
        echo "MISE_DATA_DIR=${MISE_DATA_DIR}" >> "$GITHUB_ENV"
        # Set rustup under MISE_DATA_DIR for jdz/mise-action to cache rustup
        # installed tools properly
        echo "RUSTUP_HOME=${MISE_DATA_DIR}/.rustup-home" >> "$GITHUB_ENV"
        # Isolate cargo used with mise. But don't include it in mise cache as
        # it is better to cache separately if needed.
        echo "CARGO_HOME=${RUNNER_TEMP}/.mise-cargo" >> "$GITHUB_ENV"
      shell: bash
    - name: Setup environment for mise - windows
      if: runner.os == 'Windows'
      run: |
        MISE_DATA_DIR="${RUNNER_TEMP}\.mise"
        echo "MISE_DATA_DIR=${MISE_DATA_DIR}" >> "$GITHUB_ENV"
        # Set rustup under MISE_DATA_DIR for jdz/mise-action to cache rustup
        # installed tools properly
        echo "RUSTUP_HOME=${MISE_DATA_DIR}\.rustup-home" >> "$GITHUB_ENV"
        # Isolate cargo used with mise. But don't include it in mise cache as
        # it is better to cache separately if needed.
        echo "CARGO_HOME=${RUNNER_TEMP}\.mise-cargo" >> "$GITHUB_ENV"
      shell: bash
    - name: Setup mise
      uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      env:
        GITHUB_TOKEN: ${{ github.token }}
        TEMP: ${{ runner.temp }}
      with:
        experimental: true
    - name: "Run task: ${{ inputs.task }}"
      if: ${{ inputs.task != '' }}
      run: mise run ${{ inputs.task }}
      shell: bash
