name: mise project task
description: Setup mise and tools for project and run task
inputs:
  task:
    description: Task to run. Leave empty to not run task.
    required: false
  cache_save:
    description: if false, action will not write to mise cache
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup environment for mise
      id: setup
      run: |
        set -x
        if [ "${{ runner.os }}" = "Windows" ]; then
          SEP="\\"
        else
          SEP="/"
        fi
        MISE_DATA_DIR="${RUNNER_TEMP}${SEP}.mise"
        echo "MISE_DATA_DIR=${MISE_DATA_DIR}" >> "$GITHUB_ENV"
        # Set rustup under MISE_DATA_DIR for jdz/mise-action to cache rustup
        # installed tools properly
        echo "RUSTUP_HOME=${MISE_DATA_DIR}${SEP}.rustup-home" >> "$GITHUB_ENV"
        # Isolate cargo used with mise. But don't include it in mise cache as
        # it is better to cache separately if needed.
        CARGO_HOME_FINAL="${RUNNER_TEMP}${SEP}.mise-cargo"
        echo "CARGO_HOME_FINAL=${CARGO_HOME_FINAL}" >> "$GITHUB_OUTPUT"
        # Use a directory inside MISE_DATA_DIR as CARGO_HOME during mise install
        # to allow caching of cargo binaries that mise requires to exist after
        # in order to utilize cached rustup and cargo binaries without reinstalling
        # them.
        echo "CARGO_HOME_MISE_INSTALL=${MISE_DATA_DIR}${SEP}.cargo-home" >> "$GITHUB_OUTPUT"
      shell: bash
    - name: Setup mise
      uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2.2.3
      env:
        CARGO_HOME: ${{ steps.setup.outputs.CARGO_HOME_MISE_INSTALL }}
        GITHUB_TOKEN: ${{ github.token }}
        TEMP: ${{ runner.temp }}
      with:
        cache_save: ${{ inputs.cache_save }}
        experimental: true
    - name: Prepare cargo home
      run: |
        set -x
        mkdir -p "${{ steps.setup.outputs.CARGO_HOME_MISE_INSTALL }}"
        mv "${{ steps.setup.outputs.CARGO_HOME_MISE_INSTALL }}" "${{ steps.setup.outputs.CARGO_HOME_FINAL }}"
        echo "CARGO_HOME=${{ steps.setup.outputs.CARGO_HOME_FINAL }}" >> "$GITHUB_ENV"
      shell: bash
    - name: "Run task: ${{ inputs.task }}"
      if: ${{ inputs.task != '' }}
      run: mise run ${{ inputs.task }}
      shell: bash
