name: Check - Renovate config
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup mise
        uses: ./.github/actions/mise-project-setup
      - name: Check renovate config
        run: mise run check:renovateconfig
