name: Check - Renovate config
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup mise
        uses: ./.github/actions/mise-project-setup
      - name: Check renovate config
        run: mise run check:renovateconfig
