name: Check - prettier
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  prettier:
    name: Check formatting with prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Setup mise
        uses: ./.github/actions/mise-project-setup
      - name: Check prettier
        run: mise run check:prettier
