name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  prepare-mise-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup mise and cached tools
        uses: ./.github/actions/mise-project-task
  check-prettier:
    needs: prepare-mise-cache
    uses: ./.github/workflows/check-prettier.yaml
  check-renovate-config:
    needs: prepare-mise-cache
    uses: ./.github/workflows/check-renovate-config.yaml

  check:
    needs:
      - check-prettier
      - check-renovate-config
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
