name: CI
on:
  pull_request:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  mise-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          sparse-checkout: |
            .github/actions/mise-project-setup
            mise.toml
      - name: Setup mise and cached tools
        uses: ./.github/actions/mise-project-setup
        with:
          cache-mode: prepare
  check-prettier:
    needs: mise-cache
    uses: ./.github/workflows/check-prettier.yaml
  check-renovate-config:
    needs: mise-cache
    uses: ./.github/workflows/check-renovate-config.yaml

  check:
    needs:
      - check-prettier
      - check-renovate-config
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
